language: node_js
sudo: false
node_js:
  - "8.11.1"
script:
  - cd client
  - npm install
  - git remote add heroku https://heroku:"$HEROKU_KEY"@git.heroku.com/socialfriends.git
  - git push -u heroku master

