language: node_js
sudo: false
node_js:
  - "8.11.1"
script:
  - cd server
  - git remote add heroku https://heroku:"$HEROKU_KEY"@git.heroku.com/socialfriends-api.git
  - git push -f heroku master
  - cd..
  - cd client
  - git remote add heroku https://heroku:"$HEROKU_KEY"@git.heroku.com/socialfriends.git
  - git push -f heroku master