language: node_js
sudo: false
node_js:
  - "8.11.1"
script:
  - cd server
  - npm install
# - npm run test
  - git remote add heroku https://heroku:"$HEROKU_KEY"@git.heroku.com/socialfriends-api.git
  - git push -u heroku master

